/** Source repositories powering the academy — credited on /attributions. */
export const SOURCES = [
  {
    name: "30 Days of Python",
    author: "Asabeneh Yetayeh",
    repo: "asabeneh/30-Days-Of-Python",
    url: "https://github.com/asabeneh/30-Days-Of-Python",
    license: "MIT",
    role: "「30일 파이썬 마스터」 트랙의 레슨 콘텐츠",
  },
  {
    name: "Made With ML",
    author: "Goku Mohandas",
    repo: "GokuMohandas/Made-With-ML",
    url: "https://github.com/GokuMohandas/Made-With-ML",
    license: "MIT (코드) · 레슨 © madewithml.com",
    role: "「ML 엔지니어링 & MLOps」 트랙의 레슨 및 소스 코드",
  },
  {
    name: "Stanford CS229 Cheatsheets",
    author: "Afshine & Shervine Amidi",
    repo: "afshinea/stanford-cs-229-machine-learning",
    url: "https://github.com/afshinea/stanford-cs-229-machine-learning",
    license: "MIT",
    role: "ML 레퍼런스 치트시트 (리소스 라이브러리)",
  },
  {
    name: "Project Based Learning",
    author: "practical-tutorials",
    repo: "practical-tutorials/project-based-learning",
    url: "https://github.com/practical-tutorials/project-based-learning",
    license: "참여자 보유",
    role: "프로젝트 기반 튜토리얼 (리소스 라이브러리)",
  },
  {
    name: "Awesome Machine Learning",
    author: "Joseph Misiti",
    repo: "josephmisiti/awesome-machine-learning",
    url: "https://github.com/josephmisiti/awesome-machine-learning",
    license: "CC-BY-4.0",
    role: "ML 프레임워크·라이브러리 (리소스 라이브러리)",
  },
  {
    name: "AI Engineering from Scratch",
    author: "Rohit Ghumare & contributors",
    repo: "rohitg00/ai-engineering-from-scratch",
    url: "https://github.com/rohitg00/ai-engineering-from-scratch",
    license: "MIT",
    role: "「AI 엔지니어링: 밑바닥부터」 트랙의 전체 레슨 (20 phase · 503 레슨)",
  },
  {
    name: "Developer Roadmaps (roadmap.sh)",
    author: "Kamran Ahmed",
    repo: "kamranahmedse/developer-roadmap",
    url: "https://roadmap.sh/ai-engineer",
    license: "© roadmap.sh · 링크 아웃",
    role: "「AI 엔지니어링」 보완 리소스 — 갭 진단·범위 체크 (AI Engineer / AI Agents 로드맵)",
  },
  {
    name: "AI Engineering (aie-book)",
    author: "Chip Huyen",
    repo: "chiphuyen/aie-book",
    url: "https://github.com/chiphuyen/aie-book",
    license: "© Chip Huyen (O'Reilly) · 링크 아웃",
    role: "「AI 엔지니어링」 보완 리소스 — 평가·RAG·추론 응용계층 레퍼런스",
  },
  {
    name: "Anthropic Courses",
    author: "Anthropic",
    repo: "anthropics/courses",
    url: "https://github.com/anthropics/courses",
    license: "CC BY-NC 4.0",
    role: "「AI 엔지니어링」 보완 리소스 — 프롬프트 엔지니어링·평가 실습",
  },
  {
    name: "Building Effective Agents",
    author: "Anthropic",
    repo: "anthropic.com/research",
    url: "https://www.anthropic.com/research/building-effective-agents",
    license: "© Anthropic · 링크 아웃",
    role: "「AI 엔지니어링」 보완 리소스 — 에이전트 설계 패턴 레퍼런스",
  },
  {
    name: "Hugging Face LLM Course",
    author: "Hugging Face",
    repo: "huggingface/course",
    url: "https://huggingface.co/learn/llm-course",
    license: "Apache-2.0",
    role: "「AI 엔지니어링」 보완 리소스 — 임베딩·검색",
  },
  {
    name: "Hugging Face Agents Course",
    author: "Hugging Face",
    repo: "huggingface/agents-course",
    url: "https://huggingface.co/learn/agents-course",
    license: "Apache-2.0",
    role: "「AI 엔지니어링」 보완 리소스 — 에이전트 기초·구현·트레이싱",
  },
  {
    name: "7 AI Engineering Skills",
    author: "Bashiri Smith",
    repo: "instagram.com/reel/DYPnSM_B94c",
    url: "https://www.instagram.com/reel/DYPnSM_B94c/",
    license: "© Bashiri Smith · 링크 아웃",
    role: "리소스 라이브러리 — 2026 AI 엔지니어 7대 스킬 추천 영상 큐레이션",
  },
] as const;
